export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_LOAD = 'LOGIN_LOAD';
export const LOGOUT = 'LOGOUT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_LOAD = 'REGISTER_LOAD';

export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
