export const UNFOLLOW_USER_LOAD = 'UNFOLLOW_USER_LOAD';
export const UNFOLLOW_USER_SUCCESS = 'UNFOLLOW_USER_SUCCESS';
export const UNFOLLOW_USER_ERROR = 'UNFOLLOW_USER_ERROR';

export const FOLLOW_USER_LOAD = 'FOLLOW_USER_LOAD';
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS';
export const FOLLOW_USER_ERROR = 'FOLLOW_USER_ERROR';

export const FETCH_FOLLOWING_LOAD = 'FOLLOW_USER_LOAD';
export const FETCH_FOLLOWING_SUCCESS = 'FOLLOW_USER_SUCCESS';
export const FETCH_FOLLOWING_ERROR = 'FOLLOW_USER_ERROR';

export const FETCH_USER_LOAD = 'FETCH_USER_LOAD';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
