export const SEARCH_USERS_LOAD = 'SEARCH_USERS_LOAD';
export const SEARCH_USERS_ERROR = 'SEARCH_USERS_ERROR';
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';

export const FETCH_USER_LOAD = 'FETCH_USER_LOAD';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
