export const SEND_MESSAGE = 'SEND_MESSAGE';

export const GET_MESSAGE_LOAD = 'GET_MESSAGE_LOAD';
export const GET_MESSAGE_SUCCESS = 'GET_MESSAGE_SUCCESS';
export const GET_MESSAGE_ERROR = 'GET_MESSAGE_ERROR';
